@startuml
title Deployment – SIGET

node "Cliente\n(PC / Laptop / Móvil)" as Client {
  artifact "Navegador Web"
}

node "Servidor de Aplicaciones\nSIGET" as App {
  component "SIGET Web API"
  component "Módulo Gestión Torneos"
  component "Módulo Estadísticas"
}

node "Servidor de BD\nSIGET-DB" as DB {
  database "Motor BD"
}

Client --> App : HTTP/HTTPS
App --> DB : Conexión SQL

@enduml
