@startuml
title Paquetes – Arquitectura lógica SIGET

package "ui" {
  class MatchController
  class TeamController
}

package "application" {
  class MatchAppService
  class TeamAppService
}

package "domain" {
  class Team
  class Player
  class Match
  class Referee
  enum MatchStatus
}

package "infrastructure" {
  class MatchRepository
  class TeamRepository
  class PlayerRepository
  class RefereeRepository
}

MatchController --> MatchAppService
TeamController --> TeamAppService

MatchAppService --> MatchRepository
TeamAppService --> TeamRepository

MatchRepository --> Match
TeamRepository --> Team
PlayerRepository --> Player
RefereeRepository --> Referee

@enduml
