@startuml
title Secuencia: Programar Partido
actor Admin
participant UI
participant "MatchService" as S
database "RepoTeams" as RT
database "RepoMatches" as RM
database "RepoReferees" as RR

Admin -> UI: solicitar programación (equipos, fecha/hora, sede)
UI -> S: validate(equipos !=, fecha/hora)
S -> RT: getById(home), getById(away)
S -> RR: getById(referee)
S -> RM: save(new Match)
RM --> S: matchId
S --> UI: confirmación
UI --> Admin: partido creado
@enduml