@startuml
title Secuencia – Programar partido

actor Administrador
participant "UI Web" as UI
participant "MatchController" as Ctrl
participant "MatchService" as Service
database "MatchRepository / DB" as Repo

Administrador -> UI: Completar formulario (nuevo partido)
UI -> Ctrl: POST /matches (datos)
Ctrl -> Service: validarYCrearPartido(datos)

Service -> Service: validar equipos (home != away)
Service -> Repo: crearPartido(status='scheduled')
Repo --> Service: idMatch

Service -> Repo: asignarArbitro(idMatch)
Repo --> Service: árbitro asignado

Service --> Ctrl: resultado OK (idMatch)
Ctrl --> UI: 201 Created + mensaje
UI --> Administrador: Confirmación

@enduml
